# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 664ba438c3d36a8f09fe43e18878864bc2e1667548ab529d0ef150d4c2073490316e6dda70894e5a841ea492f2278e59032f6b97c610504731b088e95bcfb8e8

test:
  secret_key_base: c74aa0818e2ef77b766ed67c7b64dd192b1a8e78101c15c336d2699000647d0e036e63688459f31722058a3713046f9a47720cf0ba2d46390666041367025016

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
